### ISSUE TITLE
Some problems with the website

### ISSUE THREAD

**Issue by RobDonovan** [anteatergames/indievisible#5]
As requested from IGDF group, here are some problems I found while testing for you:

- When editing my profile, on the 'Basic' tab, top right is a link called 'Change Cover Image'. There is no image there to show the link or button, you can only see a slight outline around where the button should be, so most people would no know it was there.

- When adding a cover image, it doesn't tell you what the image dimensions should be. If I do upload one, it's very restricted in height/width ratio, as in the height is very small. Makes it difficult to use anything standard. Also, it doesn't match what the 'crop' shows once you save.

- Same with the profile icon, doesn't tell you sizes. Only way I could get a good image in fully was do > 500x500px.

- Once you've set a cover image, it doesn't seem to let you update to another image. It all uploads, but when you refresh your profile, it's the old image. Probably some kinda caching.

- In Profile settings / External, with the Itch.io you only have to put the handle and it adds the rest of the URL to whatever you type (So if you put the full url in, it creates an invalid link). But all the others, it uses the direct URL/text you type.

- When posting a comment on a post, it says press CTRL-ENTER to send, that does nothing and you actually press that black bubble to the right of the text.

- Posting from the front page, doesn't create links with 'https' in the text. Not sure if it should or shouldn't.

- Posting from the front page, with a image, doesn't include the image, just the text.

- When posting a 'complex' post, and I try to insert a image (using the menu) I get a javascript box saying "Cannot upload file: RoKabium-Games-KatandRob_1200.jpg" and it wont let me include a file. Seemed to work with very small files, but not screenshots (ie >1000px)

- When adding a game 'Team' only has 'Just Myself'. But there are 2 of us for our game.

- When adding a game for 'Presence' and platforms there is no 'Mac' option.

- When adding a game for 'External' Itch.io I put 'rokabium-games', but the clickable link on my games front page is now: https://www.indievisible.net/game/6d838764-009b-42ab-9c9a-026c19e72ebe/rokabium-games  which is invalid.

HTHs, Rob.

**Comment by programad** [comment]
> When editing my profile, on the 'Basic' tab, top right is a link called 'Change Cover Image'. There is no image there to show the link or button, you can only see a slight outline around where the button should be, so most people would no know it was there.

Fixed!

> When adding a cover image, it doesn't tell you what the image dimensions should be. If I do upload one, it's very restricted in height/width ratio, as in the height is very small. Makes it difficult to use anything standard. Also, it doesn't match what the 'crop' shows once you save.

Fixed!

> Same with the profile icon, doesn't tell you sizes. Only way I could get a good image in fully was do 500x500px.

Fixed, set the recommendation to 512x512

> Once you've set a cover image, it doesn't seem to let you update to another image. It all uploads, but when you refresh your profile, it's the old image. Probably some kinda caching.

Fixed, you were right, the CDN was caching.

> In Profile settings / External, with the Itch.io you only have to put the handle and it adds the rest of the URL to whatever you type (So if you put the full url in, it creates an invalid link). But all the others, it uses the direct URL/text you type.

I could not replicate this one. It works for me. Maybe you could re-test or elaborate a little.

> When posting a comment on a post, it says press CTRL-ENTER to send, that does nothing and you actually press that black bubble to the right of the text.

Fixed.

> Posting from the front page, doesn't create links with 'https' in the text. Not sure if it should or shouldn't.

Fixed.

> Posting from the front page, with a image, doesn't include the image, just the text.

An error handling was missing. Fixed.

> When posting a 'complex' post, and I try to insert a image (using the menu) I get a javascript box saying "Cannot upload file: RoKabium-Games-KatandRob_1200.jpg" and it wont let me include a file. Seemed to work with very small files, but not screenshots (ie >1000px)

I could not replicate this one. Maybe there are specific steps to follow?

> When adding a game 'Team' only has 'Just Myself'. But there are 2 of us for our game.

Added the feature to create a new team when adding a game.

> When adding a game for 'Presence' and platforms there is no 'Mac' option.

Mac option added.

> When adding a game for 'External' Itch.io I put 'rokabium-games', but the clickable link on my games front page is now: https://www.indievisible.net/game/6d838764-009b-42ab-9c9a-026c19e72ebe/rokabium-games which is invalid.

Itch.io url handling improved.

@RobDonovan , Thank you for the bug report. I will continue to fix the reported issues.

**Comment by programad** [comment]
All reported issues described were solved.

@RobDonovan
